fix(deps): update prisma monorepo to v6.1.0 (#1406)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@prisma/client](https://www.prisma.io) ([source](https://redirect.github.com/prisma/prisma/tree/HEAD/packages/client)) | [`6.0.1` -> `6.1.0`](https://renovatebot.com/diffs/npm/@prisma%2fclient/6.0.1/6.1.0) | [![age](https://developer.mend.io/api/mc/badges/age/npm/@prisma%2fclient/6.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@prisma%2fclient/6.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@prisma%2fclient/6.0.1/6.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@prisma%2fclient/6.0.1/6.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [prisma](https://www.prisma.io) ([source](https://redirect.github.com/prisma/prisma/tree/HEAD/packages/cli)) | [`6.0.1` -> `6.1.0`](https://renovatebot.com/diffs/npm/prisma/6.0.1/6.1.0) | [![age](https://developer.mend.io/api/mc/badges/age/npm/prisma/6.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prisma/6.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prisma/6.0.1/6.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prisma/6.0.1/6.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>prisma/prisma (@&#8203;prisma/client)</summary>

### [`v6.1.0`](https://redirect.github.com/prisma/prisma/releases/tag/6.1.0)

[Compare Source](https://redirect.github.com/prisma/prisma/compare/6.0.1...6.1.0)

Today we're releasing Prisma ORM version 6.1.0

In this version our `tracing` Preview feature is being graduated to GA!

##### Highlights

##### Tracing goes GA

The `tracing` Preview feature is now stable. You now no longer have to include `tracing` in your set of enabled preview features.

```diff
generator client {
   provider        = "prisma-client-js"
-  previewFeatures = ["tracing"]
}
```

We have also changed some of the spans generated by Prisma Client. Previously, a trace would report the following spans:

    prisma:client:operation
    prisma:client:serialize
    prisma:engine
    prisma:engine:connection
    prisma:engine:db_query
    prisma:engine:serialize

Now, the following are reported:

    prisma:client:operation
    prisma:client:serialize
    prisma:engine:query
    prisma:engine:connection
    prisma:engine:db_query
    prisma:engine:serialize
    prisma:engine:response_json_serialization

Additionally, we have made a few changes to our dependencies:

-   `@opentelemetry/api` is now a peer dependency instead of a regular dependency
-   ` registerInstrumentations  ` in `@opentelemetry/instrumentation` is now re-exported by `@prisma/instrumentation`

After upgrading to Prisma ORM 6.1.0 you will need to add `@opentelemetry/api` to your dependencies if you haven't already:

    npm install @&#8203;opentelemetry/api

You will also no longer need to have `@opentelemetry/instrumentation` if you only use `registerInstrumentations`. In this case you can import `registerInstrumentations` from `@prisma/instrumentation`

```diff
- import { PrismaInstrumentation } from '@&#8203;prisma/instrumentation'
+ import { PrismaInstrumentation, registerInstrumentations } from '@&#8203;prisma/instrumentation'
```

##### Bug fixes

##### Tracing related

As we're moving our `tracing` preview to GA, a number of issues have been resolved. Here are a few highlights:

-   [Tests for tracing expanded and improved](https://redirect.github.com/prisma/prisma/issues/19224)
-   [Issues with Elastic APM addressed](https://redirect.github.com/prisma/prisma/issues/24715)
-   [Issues with Datadog tracer addressed](https://redirect.github.com/prisma/prisma/issues/22450)
-   [Prisma Client now respects `suppressTracing`](https://redirect.github.com/prisma/prisma/issues/17953)

##### Other issues

We also have a number of other issues that were resolved outside of our `tracing` feature.

-   [Resolved type issues with the `PrismaNeonHTTP` adapter](https://redirect.github.com/prisma/prisma/issues/25514)
-   [`findUnique` returns `null` when used instead of `Promise.all`](https://redirect.github.com/prisma/prisma/issues/25662)
-   [Resolved an issue with the latest version of Alpine Linux](https://redirect.github.com/prisma/prisma/issues/25817)

##### Fixes and improvements

##### Prisma

-   [Tracing: Detailed report and profiling informations](https://redirect.github.com/prisma/prisma/issues/1711)
-   [Prisma Client Request Tracing Integration](https://redirect.github.com/prisma/prisma/issues/5956)
-   [Instrumentation error in production: `TypeError: parentTracer.getSpanLimits is not a function`](https://redirect.github.com/prisma/prisma/issues/14887)
-   [Prisma is using the internal `Span` constructor](https://redirect.github.com/prisma/prisma/issues/16309)
-   [Prisma Client doesn't put all OTEL trace spans under one parent span](https://redirect.github.com/prisma/prisma/issues/16791)
-   [Prisma trace has unaccounted time](https://redirect.github.com/prisma/prisma/issues/17853)
-   [`prisma:engine` spans do not respect `suppressTracing()`](https://redirect.github.com/prisma/prisma/issues/17953)
-   [`tracing: engine` spans don't pass through `Sampler`](https://redirect.github.com/prisma/prisma/issues/19088)
-   [Add tests for tracing and different ways to open the first connection (including internal spans)](https://redirect.github.com/prisma/prisma/issues/19224)
-   [Tracing: Long trailing delay in `prisma:client:operation`](https://redirect.github.com/prisma/prisma/issues/19580)
-   [`prisma:engine` spans are missing when there are multiple `new PrismaClient()` invocations](https://redirect.github.com/prisma/prisma/issues/20779)
-   [`parentTracer.getSpanLimits is not a function`](https://redirect.github.com/prisma/prisma/issues/21397)
-   [Support tracers not derived from `opentelemetry-sdk-trace-base` (e.g. Datadog tracer)](https://redirect.github.com/prisma/prisma/issues/22450)
-   [`traceparent` comments with multiple SQL statements](https://redirect.github.com/prisma/prisma/issues/24370)
-   [Make `@prisma/instrumentation` dependencies peer dependencies](https://redirect.github.com/prisma/prisma/issues/24373)
-   [Make sure `db.statement` attribute doesn't include the `traceparent` comment](https://redirect.github.com/prisma/prisma/issues/24375)
-   [\[Instrumentation\] `registerInstrumentations` uses the global provider instead of the one passed in](https://redirect.github.com/prisma/prisma/issues/24488)
-   [Instrumentation: Problems in working with Elastic APM](https://redirect.github.com/prisma/prisma/issues/24715)
-   [`PrismaNeonHTTP` adapter breaks on some types e.g. timestamp](https://redirect.github.com/prisma/prisma/issues/25514)
-   [Promise.all() returns null with findUnique()](https://redirect.github.com/prisma/prisma/issues/25662)
-   [Alpine Linux 3.21: `Prisma failed to detect the libssl/openssl version to use`](https://redirect.github.com/prisma/prisma/issues/25817)

##### Prisma Client

-   [Tracing operation duration bug under stress test](https://redirect.github.com/prisma/prisma/issues/16980)
-   [`@prisma/instrumentation` Type Error: `'InstrumentionNodeModuleDefintion' is not generic`](https://redirect.github.com/prisma/prisma/issues/24285)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these updates again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/). View the [repository job log](https://developer.mend.io/github/kula-app/OnLaunch).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS43Mi41IiwidXBkYXRlZEluVmVyIjoiMzkuNzIuNSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->