fix(deps): update prisma monorepo to v4.15.0 (#297)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@prisma/client](https://www.prisma.io) ([source](https://togithub.com/prisma/prisma)) | [`4.14.1` -> `4.15.0`](https://renovatebot.com/diffs/npm/@prisma%2fclient/4.14.1/4.15.0) | [![age](https://badges.renovateapi.com/packages/npm/@prisma%2fclient/4.15.0/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/@prisma%2fclient/4.15.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/@prisma%2fclient/4.15.0/compatibility-slim/4.14.1)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/@prisma%2fclient/4.15.0/confidence-slim/4.14.1)](https://docs.renovatebot.com/merge-confidence/) |
| [prisma](https://www.prisma.io) ([source](https://togithub.com/prisma/prisma)) | [`4.14.1` -> `4.15.0`](https://renovatebot.com/diffs/npm/prisma/4.14.1/4.15.0) | [![age](https://badges.renovateapi.com/packages/npm/prisma/4.15.0/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/prisma/4.15.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/prisma/4.15.0/compatibility-slim/4.14.1)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/prisma/4.15.0/confidence-slim/4.14.1)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>prisma/prisma</summary>

### [`v4.15.0`](https://togithub.com/prisma/prisma/releases/tag/4.15.0)

[Compare Source](https://togithub.com/prisma/prisma/compare/4.14.1...4.15.0)

🌟 **Help us spread the word about Prisma by starring the repo or [tweeting](https://twitter.com/intent/tweet?text=Check%20out%20the%20latest%20@&#8203;prisma%20release%20v4.15.0%20%F0%9F%9A%80%0D%0A%0D%0Ahttps://github.com/prisma/prisma/releases/tag/4.15.0) about the release.** 🌟

##### Highlights

For this release, we focused on fixing bugs and making smaller quality-of-life improvements.

##### Support for custom arguments for `prisma db seed`

This release adds support for defining and passing arbitrary arguments to `prisma db seed`. This creates the opportunity for you to define your own arguments in your seed file that you could pass to the `prisma db seed` command. A few example use-cases include, but are not limited to:

-   Seeding different data in different environments
-   Partially seeding data in some tables

Here is an example `seed.ts` file that defines custom arguments for seeding different data in different environments:

```tsx
// prisma/seed.ts
import { parseArgs } from "node:util";

const options = {
  environment: { type: 'string', },
}

async function main() {
  const { values: { environment } } = parseArgs({ options })
  
  switch (environment) {
    case "development":
      /** do something for development */
      break;
    case "test":
      /** do something  for test  environment */
      break;
    default:
      break;
  }
}

main()
```

You can then provide the `environment` argument when executing the seed script as follows:

```bash
npx prisma db seed -- --environment development
```

Let us know what you think, share example usage of this feature, and create a [bug report](https://togithub.com/prisma/prisma/issues/new?assignees=\&labels=kind/bug\&projects=\&template=bug_report.yml) if you run into any issues.

##### Improved error messages when Query Engine file is not found

This release improves the error messages returned by Prisma Client when the Query Engine file is not found. A few reasons the Query Engine file might be missing from your application bundle include when:

-   The downloaded Query Engine doesn’t match the runtime/ target platform your application is running on.
-   The Query Engine is not copied to your final application bundle during the build step.

We hope these error messages are helpful while debugging your application.

##### Prisma VS Code extension improvements

In this release, we made a few improvements to our [VS Code extension](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma):

1.  Updated the file system watcher that is responsible for restarting the TypeScript server when `prisma generate` is run to ensure the types are in sync

    > **Note**:
    >
    > -   This new approach is currently only available on Windows and Linux. We plan on adding support for the new file system watcher on macOS soon.
    > -   This requires both Prisma CLI & VS code extension version `4.15.0` or higher

2.  Added [Quick Fixes action](https://code.visualstudio.com/docs/editor/refactoring#\_code-actions-quick-fixes-and-refactorings) for unique identifiers for MongoDB to add the `@map("_id")` attribute function when it’s missing on an identifier field

    https://user-images.githubusercontent.com/29753584/239030357-2b6613bf-b6b5-48f2-a2df-b93df0692fda.mov

3.  Support for [renaming symbols](https://code.visualstudio.com/docs/editor/refactoring#\_rename-symbol) for composite types and views

    https://user-images.githubusercontent.com/33921841/242042225-87dfee9b-0698-4e1d-b05e-5cb0b8ab1349.mov

##### Fixes and improvements

##### Prisma Client

-   [Prisma generate - `Error: write EPIPE` on WSL <-> Windows](https://togithub.com/prisma/prisma/issues/3294)
-   [`prisma generate` is blocked by `query-engine-rhel-openssl-1.0.x` opening in Notepad on Windows](https://togithub.com/prisma/prisma/issues/4308)
-   [Generated client output path hardcoded to build environment](https://togithub.com/prisma/prisma/issues/7228)
-   [Issue with Yarn Workspace Monorepo: Query engine binary for current platform could not be found.](https://togithub.com/prisma/prisma/issues/7311)
-   [Cloning a project with checked in `node_modules` (from another platform) leads to platform engine not being present](https://togithub.com/prisma/prisma/issues/7848)
-   [SvelteKit, Vite and Prisma "module not defined"](https://togithub.com/prisma/prisma/issues/10404)
-   [Schema File Not Found in non monorepo with custom `output`](https://togithub.com/prisma/prisma/issues/10433)
-   [Deploying to Cloudflare Workers | "PrismaClient is unable to be run in the browser"](https://togithub.com/prisma/prisma/issues/12981)
-   [Inline/bundle the contents of the prisma schema on generate](https://togithub.com/prisma/prisma/issues/13052)
-   [Netlify: `Query engine library for current platform "rhel-openssl-1.0.x" could not be found. You incorrectly pinned it to rhel-openssl-1.0.x`](https://togithub.com/prisma/prisma/issues/13266)
-   [Query Engine Library Not Found](https://togithub.com/prisma/prisma/issues/13396)
-   [No client schema when using PrismaClient during cached (standard) Netlify build](https://togithub.com/prisma/prisma/issues/13475)
-   [Module "@&#8203;prisma/client" has no exported member "PrismaClient"](https://togithub.com/prisma/prisma/issues/13946)
-   [EPERM: operation not permitted](https://togithub.com/prisma/prisma/issues/14626)
-   [prisma/client crashes when used with older versions of react-refresh](https://togithub.com/prisma/prisma/issues/14953)
-   [Unable to run prisma cli in pnpm monorepo from workspace install](https://togithub.com/prisma/prisma/issues/15081)
-   [Misleading error message when the query engine is not found](https://togithub.com/prisma/prisma/issues/15292)
-   [When setting custom client output directory, generated package.json does not include "sideEffects: false"](https://togithub.com/prisma/prisma/issues/15301)
-   [ You already added the platform "debian-openssl-1.1.x" to the "generator" block in the "schema.prisma" file as described in https://pris.ly/d/client-generator, but something went wrong. ](https://togithub.com/prisma/prisma/issues/15631)
-   [Prisma seems to be looking in the wrong location for rhel-openssl-1.0.x](https://togithub.com/prisma/prisma/issues/15638)
-   [Can't find prisma engine](https://togithub.com/prisma/prisma/issues/16872)
-   [`Cannot find name '$PrismaModel'` due to feature `extendedWhereUnique` with preview feature `fieldReference`](https://togithub.com/prisma/prisma/issues/16997)
-   [Netlify build fails with PrismaClientInitializationError](https://togithub.com/prisma/prisma/issues/17167)
-   [i'm getting the error while requesting the api ](https://togithub.com/prisma/prisma/issues/17906)
-   [Query engine library for current platform could not be found.](https://togithub.com/prisma/prisma/issues/17996)
-   [Prisma unable to reconnect if initial connection fails](https://togithub.com/prisma/prisma/issues/18071)
-   [GraphQL protocol encoder incorrectly turns empty array into empty object.](https://togithub.com/prisma/prisma/issues/18846)
-   [GraphQL protocol: Invalid `Date` values silently turn into `nulls`](https://togithub.com/prisma/prisma/issues/18970)
-   [@&#8203;prisma/client/edge + Cloudflare Worker / wrangler = Could not resolve "os"](https://togithub.com/prisma/prisma/issues/19174)
-   [Client is bricked from connecting to DB if first attempt fails.](https://togithub.com/prisma/prisma/issues/19182)
-   [JSON protocol: incorrect recursive composites detection through multiple nesting levels](https://togithub.com/prisma/prisma/issues/19373)
-   [`fieldReference` is not working with enums](https://togithub.com/prisma/prisma/issues/19449)

##### Prisma Migrate

-   [Pass extra arguments to `prisma db seed` to the seed command](https://togithub.com/prisma/prisma/issues/9403)
-   [Typo in generating migration SQL to add enum.](https://togithub.com/prisma/prisma/issues/19352)

##### Language tools (e.g. VS Code)

-   [MongoDB: Quick fix for missing `@map("_id")` annotation](https://togithub.com/prisma/language-tools/issues/762)
-   [Rename composite types](https://togithub.com/prisma/language-tools/issues/1135)
-   [Views: Support for rename](https://togithub.com/prisma/language-tools/issues/1365)
-   [TextDocument deprecation](https://togithub.com/prisma/language-tools/issues/1421)
-   [Lib name change vsce -> @&#8203;vscode/vsce](https://togithub.com/prisma/language-tools/issues/1425)

##### Credits

Huge thanks to [@&#8203;RobertCraigie](https://togithub.com/RobertCraigie), [@&#8203;KhooHaoYit](https://togithub.com/KhooHaoYit), [@&#8203;art049](https://togithub.com/art049), [@&#8203;luxaritas](https://togithub.com/luxaritas), [@&#8203;mrazauskas](https://togithub.com/mrazauskas), [@&#8203;maxmartynov](https://togithub.com/maxmartynov), [@&#8203;haneenmahd](https://togithub.com/haneenmahd) for helping!

##### 📺 Join us for another "What's new in Prisma" live stream

Learn about the latest release and other news from the Prisma community by joining us for another ["What's new in Prisma"](https://youtube.com/playlist?list=PLn2e1F9Rfr6l1B9RP0A9NdX7i7QIWfBa7) live stream.

The stream takes place [on YouTube](https://youtu.be/t7jsqf0DeNc) on **Thursday, June 1** at **5 pm Berlin | 8 am San Francisco**.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these updates again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://app.renovatebot.com/dashboard#github/kula-app/OnLaunch).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNS4xMDIuMTAiLCJ1cGRhdGVkSW5WZXIiOiIzNS4xMDIuMTAiLCJ0YXJnZXRCcmFuY2giOiJtYWluIn0=-->